const countriesData = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo, Democratic Republic of the",
  "Congo, Republic of the",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, North",
  "Korea, South",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

const subjectsData = [
  { label: "Mathematics", value: "mathematics" },
  { label: "Physics", value: "physics" },
  { label: "Chemistry", value: "chemistry" },
  { label: "Biology", value: "biology" },
  { label: "Computer Science", value: "computer science" },
  { label: "History", value: "history" },
  { label: "Geography", value: "geography" },
  { label: "Literature", value: "literature" },
  { label: "Philosophy", value: "philosophy" },
  { label: "Psychology", value: "psychology" },
  { label: "Economics", value: "economics" },
  { label: "Political Science", value: "political science" },
  { label: "Sociology", value: "sociology" },
  { label: "Anthropology", value: "anthropology" },
  { label: "Linguistics", value: "linguistics" },
  { label: "Art", value: "art" },
  { label: "Music", value: "music" },
  { label: "Drama", value: "drama" },
  { label: "Dance", value: "dance" },
  { label: "Physical Education", value: "physical education" },
  { label: "Health", value: "health" },
  { label: "Environmental Science", value: "environmental science" },
  { label: "Business Studies", value: "business studies" },
  { label: "Law", value: "law" },
  { label: "Engineering", value: "engineering" },
  { label: "Medicine", value: "medicine" },
  { label: "Nursing", value: "nursing" },
  { label: "Dentistry", value: "dentistry" },
  { label: "Pharmacy", value: "pharmacy" },
  { label: "Veterinary Science", value: "veterinary science" },
  { label: "Agriculture", value: "agriculture" },
  { label: "Forestry", value: "forestry" },
  { label: "Architecture", value: "architecture" },
  { label: "Urban Planning", value: "urban planning" },
  { label: "Journalism", value: "journalism" },
  { label: "Media Studies", value: "media studies" },
  { label: "Film Studies", value: "film studies" },
  { label: "Theology", value: "theology" },
  { label: "Religious Studies", value: "religious studies" },
  { label: "Education", value: "education" },
  { label: "Special Education", value: "special education" },
  { label: "Social Work", value: "social work" },
  { label: "Criminology", value: "criminology" },
  { label: "Public Administration", value: "public administration" },
  { label: "International Relations", value: "international relations" },
];

//////////////////////////////
//////////////////////////////
//////////////////////////////
//////////////////////////////
//////// KEY - VALUE /////////
//////////////////////////////
//////////////////////////////
//////////////////////////////
// LOCATION
const countriesKeyValue = [
  { label: "United States", value: "US" },
  { label: "China", value: "CN" },
  { label: "India", value: "IN" },
  { label: "Brazil", value: "BR" },
  { label: "United Kingdom", value: "GB" },
  { label: "Germany", value: "DE" },
  { label: "France", value: "FR" },
  { label: "Japan", value: "JP" },
  { label: "Russia", value: "RU" },
  { label: "Canada", value: "CA" },
  { label: "Australia", value: "AU" },
  { label: "Italy", value: "IT" },
  { label: "South Korea", value: "KR" },
  { label: "Mexico", value: "MX" },
  { label: "Indonesia", value: "ID" },
  { label: "South Africa", value: "ZA" },
  { label: "Saudi Arabia", value: "SA" },
  { label: "Argentina", value: "AR" },
  { label: "Turkey", value: "TR" },
  { label: "Spain", value: "ES" },
];

// LANGUAGES
const languagesKeyValue = [
  { label: "English", value: "en" },
  { label: "Mandarin Chinese", value: "zh" },
  { label: "Spanish", value: "es" },
  { label: "Hindi", value: "hi" },
  { label: "French", value: "fr" },
  { label: "Arabic", value: "ar" },
  { label: "Bengali", value: "bn" },
  { label: "Portuguese", value: "pt" },
  { label: "Russian", value: "ru" },
  { label: "Japanese", value: "ja" },
  { label: "Punjabi", value: "pa" },
  { label: "German", value: "de" },
  { label: "Javanese", value: "jv" },
  { label: "Korean", value: "ko" },
  { label: "Telugu", value: "te" },
  { label: "Vietnamese", value: "vi" },
  { label: "Marathi", value: "mr" },
  { label: "Tamil", value: "ta" },
  { label: "Italian", value: "it" },
  { label: "Urdu", value: "ur" },
];

// SUBJECTS
const subjectsKeyValue = [
  { label: "Mathematics", value: "math" },
  { label: "Physics", value: "physics" },
  { label: "Chemistry", value: "chemistry" },
  { label: "Biology", value: "biology" },
  { label: "Computer Science", value: "cs" },
  { label: "History", value: "history" },
  { label: "Geography", value: "geography" },
  { label: "Economics", value: "economics" },
  { label: "English Literature", value: "english-lit" },
  { label: "Philosophy", value: "philosophy" },
  { label: "Political Science", value: "political-science" },
  { label: "Psychology", value: "psychology" },
  { label: "Sociology", value: "sociology" },
  { label: "Art", value: "art" },
  { label: "Music", value: "music" },
  { label: "Environmental Science", value: "environmental-science" },
  { label: "Law", value: "law" },
  { label: "Business Studies", value: "business-studies" },
  { label: "Medicine", value: "medicine" },
  { label: "Engineering", value: "engineering" },
];

// Topic
const subTopicsKeyValue = [
  { label: "Algebra", value: "algebra" },
  { label: "Quantum Mechanics", value: "quantum-mechanics" },
  { label: "Organic Chemistry", value: "organic-chemistry" },
  { label: "Genetics", value: "genetics" },
  { label: "Artificial Intelligence", value: "ai" },
  { label: "World War II", value: "ww2" },
  { label: "Human Geography", value: "human-geography" },
  { label: "Microeconomics", value: "microeconomics" },
  { label: "Shakespearean Drama", value: "shakespeare" },
  { label: "Ethics", value: "ethics" },
  { label: "Constitutional Law", value: "constitutional-law" },
  { label: "Cognitive Psychology", value: "cognitive-psychology" },
  { label: "Social Stratification", value: "social-stratification" },
  { label: "Renaissance Art", value: "renaissance-art" },
  { label: "Music Theory", value: "music-theory" },
  { label: "Climate Change", value: "climate-change" },
  { label: "Corporate Law", value: "corporate-law" },
  { label: "Entrepreneurship", value: "entrepreneurship" },
  { label: "Cardiology", value: "cardiology" },
  { label: "Civil Engineering", value: "civil-engineering" },
];
