const sizemugGlobalInterests = [
  { label: "Fitness", value: "fitness" },
  { label: "Wellness", value: "wellness" },
  { label: "Health", value: "health" },
  { label: "Beauty", value: "beauty" },
  { label: "Concerts", value: "concerts" },
  { label: "Music", value: "music" },
  { label: "Gaming", value: "gaming" },
  { label: "Politics", value: "politics" },
  { label: "Technology", value: "technology" },
  { label: "Entrepreneurship", value: "entrepreneurship" },
  { label: "Finance", value: "finance" },
  { label: "Religion", value: "religion" },
  { label: "Spirituality", value: "spirituality" },
  { label: "Cooking", value: "cooking" },
  { label: "Pets", value: "pets" },
  { label: "Animals", value: "animals" },
  { label: "Psychology", value: "psychology" },
];
